# Feature: webull-mcp-server, Property 13: SDK Exception No Crash
# Feature: webull-mcp-server, Property 14: Market Data 403 Subscription Guidance
# Feature: webull-mcp-server, Property 17: Log Channel Isolation
"""Property-based tests for MCP Server integration.

Validates: Requirements 16.1, 16.2, 16.4, 3.3, 6.6, 16.3, 1.2, 15.2

Note: Properties 12 (Tool Annotation Correctness) and 16 (Tool Metadata
Completeness) were removed because they relied on the old TOOL_DEFINITIONS
list which no longer exists in the FastMCP architecture. Tool metadata is
now auto-generated by FastMCP from function signatures and @mcp.tool()
decorators.
"""

from __future__ import annotations

import asyncio
import logging
import sys
from unittest.mock import MagicMock, patch

import pytest

from webull_openapi_mcp.audit import AuditLogger
from webull_openapi_mcp.config import ServerConfig
from webull_openapi_mcp.errors import _get_market_data_hint, handle_sdk_exception


_NO_ACCESS_MSG = "no access"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _config(**overrides) -> ServerConfig:
    defaults = dict(app_key="test_key", app_secret="test_secret")
    defaults.update(overrides)
    return ServerConfig(**defaults)


# ---------------------------------------------------------------------------
# Mock exceptions
# ---------------------------------------------------------------------------

class _MockServerException(Exception):
    """Stand-in for webull ServerException."""

    def __init__(self, http_status=500, error_code="ERR", error_msg="fail"):
        self.http_status = http_status
        self.error_code = error_code
        self.error_msg = error_msg
        super().__init__(error_msg)


class _MockClientException(Exception):
    """Stand-in for webull ClientException."""

    def __init__(self, error_code="PARAM_ERR", error_msg="bad param"):
        self.error_code = error_code
        self.error_msg = error_msg
        super().__init__(error_msg)


def _patch_exceptions():
    """Return a context manager that patches webull exception classes."""
    fake_exceptions = MagicMock()
    fake_exceptions.ServerException = _MockServerException
    fake_exceptions.ClientException = _MockClientException
    return patch.dict(
        "sys.modules",
        {"webull.core.exception.exceptions": fake_exceptions},
    )


# ---------------------------------------------------------------------------
# Property 13: SDK Exception No Crash
# **Validates: Requirements 16.1, 16.2, 16.4, 3.3**
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "exc_factory,expected_fragment",
    [
        (
            lambda: _MockServerException(500, "SVR_ERR", "internal"),
            "Server error",
        ),
        (
            lambda: _MockClientException("CLI_ERR", "bad input"),
            "Parameter error",
        ),
    ],
    ids=["ServerException", "ClientException"],
)
def test_property13_handle_sdk_exception(exc_factory, expected_fragment):
    """handle_sdk_exception returns a structured error string for both
    ServerException and ClientException."""
    exc = exc_factory()
    with _patch_exceptions():
        result = handle_sdk_exception(exc, "test_tool")
    assert isinstance(result, str)
    assert expected_fragment in result


def test_property13_sdk_exception_via_registered_tool():
    """When SDK raises inside a registered tool, the tool returns an error
    string instead of crashing. Tests via the cancel_order tool."""
    pytest = __import__("pytest")
    fastmcp = pytest.importorskip("fastmcp")
    FastMCP = fastmcp.FastMCP

    sdk = MagicMock()
    sdk.trade.order_v3.cancel_order.side_effect = _MockServerException(
        500, "SVR_ERR", "SDK boom"
    )
    audit = AuditLogger(_config())

    mcp = FastMCP("test")
    from webull_openapi_mcp.tools.trading.order import register_order_tools
    register_order_tools(mcp, sdk, audit)

    # Get the registered tool function via public API
    tool = asyncio.get_event_loop().run_until_complete(mcp.get_tool("cancel_order"))
    assert tool is not None, "cancel_order tool not registered"

    with _patch_exceptions():
        result = asyncio.get_event_loop().run_until_complete(
            tool.fn(account_id="a1", client_order_id="o1")
        )
    assert isinstance(result, str)
    assert "SDK boom" in result or "Server error" in result


# ---------------------------------------------------------------------------
# Property 14: Market Data 403 Subscription Guidance
# **Validates: Requirements 6.6, 16.3**
# ---------------------------------------------------------------------------

def test_property14_market_data_403_hint():
    """When a market data tool gets a 403 ServerException, handle_sdk_exception
    returns the subscription guidance text."""
    server_exc = _MockServerException(
        http_status=403, error_code="FORBIDDEN", error_msg=_NO_ACCESS_MSG
    )
    with _patch_exceptions():
        result = handle_sdk_exception(server_exc, "get_stock_snapshot", "us")
    assert _get_market_data_hint("us") in result


@pytest.mark.parametrize(
    "tool_name",
    [
        "get_stock_snapshot",
        "get_stock_quotes",
        "get_stock_bars",
        "get_stock_tick",
        "get_futures_tick",
        "get_crypto_snapshot",
        "get_event_tick",
    ],
    ids=["stock_snapshot", "stock_quotes", "stock_bars", "stock_tick",
         "futures_tick", "crypto_snapshot", "event_tick"],
)
def test_property14_market_data_403_all_tools(tool_name):
    """All market data tools return subscription guidance on 403."""
    server_exc = _MockServerException(
        http_status=403, error_code="FORBIDDEN", error_msg=_NO_ACCESS_MSG
    )
    with _patch_exceptions():
        result = handle_sdk_exception(server_exc, tool_name, "us")
    expected = _get_market_data_hint("us")
    assert expected in result, f"{tool_name} should return subscription hint on 403"


def test_property14_via_registered_stock_snapshot():
    """End-to-end: registered get_stock_snapshot tool returns subscription
    guidance on 403 ServerException."""
    pytest = __import__("pytest")
    fastmcp = pytest.importorskip("fastmcp")
    FastMCP = fastmcp.FastMCP

    server_exc = _MockServerException(
        http_status=403, error_code="FORBIDDEN", error_msg=_NO_ACCESS_MSG
    )
    sdk = MagicMock()
    sdk.data.market_data.get_snapshot.side_effect = server_exc
    audit = AuditLogger(_config())
    config = _config()

    mcp = FastMCP("test")
    from webull_openapi_mcp.tools.market_data.stock import register_stock_market_data_tools
    register_stock_market_data_tools(mcp, sdk, audit, config)

    # Get the registered tool function via public API
    tool = asyncio.get_event_loop().run_until_complete(mcp.get_tool("get_stock_snapshot"))

    with _patch_exceptions():
        result = asyncio.get_event_loop().run_until_complete(
            tool.fn(symbols="AAPL")
        )
    assert _get_market_data_hint("us") in result


# ---------------------------------------------------------------------------
# Property 17: Log Channel Isolation
# **Validates: Requirements 1.2, 15.2**
# ---------------------------------------------------------------------------

def test_property17_audit_logs_go_to_stderr(capsys):
    """AuditLogger writes all output to stderr, nothing to stdout."""
    config = _config()
    audit = AuditLogger(config)

    # Emit various audit events
    audit.log_tool_call("test_tool", {"key": "value"})
    audit.log_order_attempt("AAPL", "BUY", 10, "MARKET", "o1", "a1")
    audit.log_order_result("o1", True, {"status": "ok"})
    audit.log_validation_error("test_tool", "some error", {"x": 1})

    captured = capsys.readouterr()
    # stdout must be empty — all output goes to stderr
    assert captured.out == "", "Audit logs must not write to stdout"
    # stderr should contain the log lines
    assert "TOOL_CALL" in captured.err
    assert "ORDER_ATTEMPT" in captured.err
    assert "ORDER_RESULT" in captured.err
    assert "VALIDATION_ERROR" in captured.err


def test_property17_logger_handlers_target_stderr():
    """All handlers on the AuditLogger's internal logger write to stderr,
    not stdout."""
    config = _config()
    audit = AuditLogger(config)

    for handler in audit._logger.handlers:
        if isinstance(handler, logging.StreamHandler) and not isinstance(
            handler, logging.FileHandler
        ):
            assert handler.stream is sys.stderr, (
                "StreamHandler must target sys.stderr, not sys.stdout"
            )
